### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by TurkDesk** [QdbS/qdbs#3]
`                    if ($row2['ip'] != $ip) {
                        $rate = $tpl->fetch($tpl->tdir.'quote_rate.tpl');
                        $tpl->set('q_rate', $rate);
                    } else {
                        $tpl->set('q_rate', '');
                    }`

index.php on line 139
index.php on line 159
index.php on line 199
index.php on line 259

Seems there is an issue with these parts.

**Comment by jobe1986** [comment]
I've pushed a fix to the git repo if you would be so kind as to test it for me please.

**Comment by TurkDesk** [comment]
Fixed most seems some new ones here with random page;

 Notice: Undefined property: QdbS_Database::$rand in index.php on line 204
 Notice: Undefined property: QdbS_Database::$rand in /index.php on line 185
 Fatal error: QdbS_Database::_sql(); -> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 10 OFFSET 0' at line 1 in /classes.php on line 200

And search and add page;

Rows:
Notice: Undefined variable: r_count in /layout_footer.tpl on line 6
; Queries:
Notice: Undefined variable: q_count in /layout_footer.tpl on line 6

**Comment by jobe1986** [comment]
With regard the first errors, there hasn't been a "QdbS_Database" class since PostgreSQL support was added, at this point there is QdbS_Database_MySQL and QdbS_Database_PgSQL both of which have a rand var.

As for the r_count and q_count, those should be fixed in the current head.

**Comment by TurkDesk** [comment]
Agreed, all cleared now well done :)
